// Generated by CoffeeScript 1.6.3
(function() {
  var directives;

  directives = angular.module('eslNgRating', []);

  directives.directive('starRating', function() {
    return {
      restrict: 'EA',
      template: '<span tooltip="{{ srTooltip }}"> <span class=stars-group > <span class="star-rating" ng-repeat="star in stars" ng-class="{true: \'star-empty\', false: \'star\'}[star.empty]"><i class="fa fa-star"></i></span> </span> <span style="color: #{{ color }}; width: {{ width }}" class="stars-group--hover"> <span class="star-rating--hover" ng-repeat="star in stars" ng-class="{true: \'star-empty\', false: \'star\'}[star.empty]"><i class="fa fa-star"></i></span> </span> <span class="grade" ng-if="showGrade">{{ value }}</span> </span>',
      link: function(scope, element, $attr) {
        scope.$watch('value', function(val, newVal) {
          var i, value, _i, _ref;
          if (val !== void 0) {
            value = Math.round(scope.value);
            if (scope.maxRating == null) {
              scope.maxRating = 5;
            }
            scope.showGrade = $attr.showGrade !== void 0 ? true : false;
            scope.stars = [];
            scope.color = ['e11e21', 'ff5d10', 'e8800e', 'f9b836', 'fdd119'][value - 1];
            scope.width = scope.value * 20 + '%';
            for (i = _i = 0, _ref = scope.maxRating; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
              scope.stars.push({
                empty: i >= value,
                index: i + 1
              });
            }
          }
        });
      },
      scope: {
        value: '=',
        maxRating: '=?',
        srTooltip: '=?'
      }
    };
  });

}).call(this);
